### ISSUE TITLE
Address field on entry and profile screens

### ISSUE THREAD

**Issue by sencode** [covenantproject/cov-pat-mobileapp#15]
On the Self registration screen, for the Address fields, (the following tooltips were taken from 

- make line 1 required, add tooltip 'Flat, House no., Building, Company, Apartment' in the background.
- make line 2 optional, add tooltip 'Area, Colony, Street, Sector, Village' in the background
- make line 3 optional, add tooltip 'Landmark'

For City, add tooltip 'City/town/taluk' in the background

Move state above district. Make state a dropdown of all the Indian states. I have loaded a list of these in the LocationHierarchy table in the Azure server.

District can be a text field for now. After a list of districts in India is added to the LocationHierarchy table, this can be converted into a dropdown.

Make PIN Code required, only accept 6 digits - numbers, no space in between. If they try to leave it empty and submit, show a tooltip for PIN Code field that it is required and 'enter 000000 if not known'.

In the profile table, just show a caption of the address type, and then show the address as text right underneath the address type. Trim all the empty lines when a field was left blank. Use the following format for concatenation. E.g.:

Temporary residence:
4 Old Jail Road
Line 2, don't show empty line if left blank
Line 3, don't show empty line if left blank
Chennai, Chennai Dist
Tamil Nadu 600001

This will be easier to read and take less space than numerous text boxes for each line of the address.

**Comment by SyedQantler** [comment]
Completed Address, City fields. State field with dropdown loaded from db and the validations mentioned. Profile screen changes also done. Please check latest release in the commit: 3acc6ddceebceb4a556845da8029f845e74a01b4
