### ISSUE TITLE
Self registration - An error occurred

### ISSUE THREAD

**Issue by sencode** [covenantproject/cov-pat-mobileapp#2]
Screenshot attached. Error happens when I fill the information and click the register button.

Phone/OS: Nokia 7.1 / Android 10.

![Screenshot_20200423-153301](https://user-images.githubusercontent.com/13280559/80152015-2ca80500-8578-11ea-8077-72e08809577b.png)

**Comment by NaveenBalakrishnan1** [comment]
Fixed
