### ISSUE TITLE
New English strings file for covenant2542020.apk

### ISSUE THREAD

**Issue by sencode** [covenantproject/cov-pat-mobileapp#5]
Can you use the attached file for English strings, please. I changed the extension to .txt because .json is not allowed by github issues. Thanks.

[en.json.txt](https://github.com/covenantproject/cov-pat-mobileapp/files/4532447/en.json.txt)

**Comment by NaveenBalakrishnan1** [comment]
will add this en.json in the build

**Comment by sencode** [comment]
Has this been added? The latest version today still shows the old strings for many fields.

**Comment by SyedQantler** [comment]
Please find the attached latest json file we have modified. Please review. This is used in the latest apk in the commit: 3acc6ddceebceb4a556845da8029f845e74a01b4

[en_json.txt](https://github.com/covenantproject/cov-pat-mobileapp/files/4561578/en_json.txt)

**Comment by SyedQantler** [comment]
Updated en.json file for your reference.
[en.json.txt](https://github.com/covenantproject/cov-pat-mobileapp/files/4588579/en.json.txt)

Latest APK Commit: 451bd70d140700bb7d41d2c32b0d5dcbbd4762b0
